name: Build

on: push

jobs:

  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          java-package: jdk
          architecture: x64

      - name: Build
        run: |
          ./gradlew -i build
